project:
  type: website
  output-dir: docs
  pre-render: scripts/install-dep.R

website:
  title: "Stat Stuff"
  favicon: "images/icon.png"
  sidebar:
    logo: "images/logo.png"
    style: "floating"
    search: true
    contents: 
      - section: "Info"
        contents:
          - about.qmd
          - times.qmd
      - section: "Lab Slides"
        contents: 
          - lab-use.qmd
          - section: "STAT 33B (Fall 2022)"
            contents:
            - stat33b/lab01.qmd
            - stat33b/lab02.qmd
            - stat33b/lab03.qmd
            - stat33b/lab04.qmd
            - stat33b/lab05.qmd
            - stat33b/lab06.qmd
            - stat33b/lab07.qmd
            - stat33b/lab08.qmd
            - stat33b/lab09.qmd
          - section: "STAT 133 (Spring 2023)"
            contents:
            - stat133/lab01.qmd
            - stat133/lab02.qmd
            - stat133/lab03.qmd
            - stat133/lab04.qmd
            - stat133/lab05.qmd
            - stat133/lab06.qmd
            - stat133/lab08.qmd
              stat133/lab09.qmd
      - section: "Notes"
      - section: "Practice Problems"
        contents:
          - practice/practice-vector.qmd
          - practice/algorithmic-problems.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
