project:
  type: website
  output-dir: docs

website:
  title: "stat33b"
  favicon: "images/icon.png"
  sidebar:
    logo: "images/logo.png"
    style: "floating"
    search: true
    contents: 
      - section: "Info"
        contents:
          - about.qmd
          - times.qmd
      - section: "Lab Slides"
        contents: 
          - lab-use.qmd
          - lab01.qmd
          - lab02.qmd
          - lab03.qmd
      - section: "Notes"
      - section: "Practice Problems"

format:
  html:
    theme: default
    css: styles.css
    toc: true